# Generated by Django 3.1.7 on 2021-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_auto_20210922_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mob',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
