# Generated by Django 3.1.7 on 2021-09-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0009_post_replie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replie',
            name='post',
        ),
        migrations.RemoveField(
            model_name='replie',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Replie',
        ),
    ]
